server:
  port: 8084
xncoding:
  muti-datasource-open: true #是否开启多数据源(true/false)
logging:
  level:
    com.youjia.springcloud: debug
mybatis-plus:
  # config-location: classpath:mybatis/mybatis-config.xml
  typeAliasesPackage: com.youjia.springcloud.pojo
  mapperLocations: classpath:mybatis/mapper/*.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spcloudb01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#多数据源
biz:
  datasource:
    url: jdbc:mysql://localhost:3306/spcloudb02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
