server:
  port: 8001
#  servlet:
#    context-path: /
logging:
  level:
    com.youjia.springcloud: debug
    org.springframework: info
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.youjia.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:  # config-location 与 configuration只能配置一个
#    map-underscore-to-camel-case: true
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spcloudb01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka
  instance:
    # 修改eureka上面的默认信息
    instance-id: springcloud-provider-dept8001

# info配置
info:
  app.name: youjia-springcloud-8001
  company.name: org.youjia.com

# 使用Hystrix Metrics Stream必备
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream