server:
  port: 8092

logging:
  level:
    com.youjia.springcloud: debug
    org.springframework: info
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.youjia.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spcloudb01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456